api_message_list:
    path: /
    controller: App\Module\Message\Application\Controller\MessageController::list
    methods: [GET]

api_message_get:
    path: /{id}
    controller: App\Module\Message\Application\Controller\MessageController::getMessage
    methods: [GET]
